### ISSUE TITLE
Mention mini-arm-os

### ISSUE THREAD

**Issue by jserv** [IoTPanic/verbose-carcrash#1]
It is my pleasure to see that partial efforts of [mini-arm-os](https://github.com/jserv/mini-arm-os) can be reused here. However, since mini-arm-os was built by the faculty and students of National Cheng Kung University, I would like to ask you to mention mini-arm-os and its copyright owner.

Author information: https://github.com/jserv/mini-arm-os/blob/master/AUTHORS

**Comment by IoTPanic** [comment]
Aha, okay, I put "Massive thanks to @jserv and his mini-arm-os which I also stole to start with." in 4184329 but I am more than happy to put that in. I am just getting started with operating systems (Though I am very familiar with arm microcontrollers and their bootloaders) and your code has been an excellent resource.

Please see the change in abce3f8 which should be shown on the master branch. Close if it is OK.

**Comment by jserv** [comment]
Thanks for prompt reply! You don't have to list the names in `REAMDME.md`. Instead, you can say,
>  "mini-arm-os was copyrighted by National Cheng Kung University, freely redistributable under the two-clause BSD License."
